### PR TITLE
Add experimental Zarr file reader/writer

### PR DESCRIPTION
**Pull request by lassoan**
The file reader/writer will eventually read/write OME-NGFF files and may be also used as a basis for adding support for other Zarr-based file formats.

### CODE REVIEW

**Comment by gaoyi** [comment]
Thanks Andras,

When compiling, the cmake step complains about missing
Resources/UI/NgffImageIO.ui
Resources/Icons/NgffImageIO.png

Should we add any specific ui and icon files?

**Comment by lassoan** [comment]
Thanks for testing, these files are not needed and should be removed from the CMakeLists.txt. I'll force-push an update in a couple of minutes.

**Comment by lassoan** [comment]
I've pushed the update, please test it. Thank you!

**Comment by lassoan** [comment]
@gaoyi Please check and integrate if it looks good now.

**Comment by gaoyi** [comment]
Thanks Andras!

Could you provide a link for a testing zarr file?

**Comment by lassoan** [comment]
The module's selftest actually creates a data set from the MRHead sample data set:

https://github.com/gaoyi/SlicerBigImage/blob/main/NgffImageIO/NgffImageIO.py#L317-L333

**Comment by lassoan** [comment]
For microscopy images, you may find this converter useful: https://www.glencoesoftware.com/pressreleases/2022-09-20-glencoe-software-releases-ngff-converter-for-generating-cloud-ready-bioimaging-data.html

It cerates ome-zarr file format, which is not xarray-compatible yet (because xarray requires image sizes to be the same across the same axis in all data sets), so instead of using xarray you could use https://pypi.org/project/ome-zarr/ package for reading/writing.

**Pull request merged**
